### create user
PUT http://localhost:9000/api/users HTTP/1.1

{
    "name": "sandra nuñez",
    "age": "57",
    "email": "svnu49@gmail.com"
}

### get all users
GET http://localhost:9000/api/users HTTP/1.1

{}

### find user
GET http://localhost:9000/api/users/6378007c1b8fd430bdd7e95d HTTP/1.1

{}